
name: corp reusable workflow
on: push


permissions:
  id-token: write
  contents: read

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: https://bananamoti.jfrog.io
      with:
        oidc-provider-name: jf-provider
